export enum ROUTE {
    GENERATEOTP = '/login/generateOTP',
    LOGIN = '/login',
    LOGOUT = '/logout',
    REGISTER = '/register',
    LANDING = '/',
    RENTALPROPERTIES = '/rental_property/all',
    RENTALPROPERTIESBYUSER = '/rental_property/allByUser',
    BOOKPROPERTY = '/booking/add',
    USER = '/user',
    USERBYEMAIL = '/userEmail',
    UPDATEPASSWORD = '/update-password',
    FORGOTPASSWORD = '/forgot-password',
    RESTPASSWORD = '/reset-password',
}
