export enum ROUTE {
    GENERATEOTP = '/login/generateOTP',
    LOGIN = '/login',
    LOGOUT = '/logout',
    REGISTER = '/register',
    LANDING = '/',
    USER = '/user',
    UPDATEPASSWORD = '/update-password',
    FORGOTPASSWORD = '/forgot-password',
    RESTPASSWORD = '/reset-password',
    RENTALPROPERTIES = '/rental_property/all',
    RENTALPROPERTYBYID = '/rental_property',
    RENTALPROPERTIESBYUSER = '/rental_property/allByUser',
    BOOKPROPERTY = '/booking/add',
    BOOKINGSBYUSER = '/booking/getAllByUser',
    CANCELBOOKING = '/booking',
    CREATEREVIEW = '/review/add',
}