spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: none
    show-sql=true:sql:
    init:
      mode: never
  profiles:
    active: bootstrap
  database:
    entityManager: javax.persistence.EntityManagerFactory
    transactionManager: org.springframework.orm.jpa.JpaTransactionManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  rabbitmq:
    exchange:
      name: logs_exchange
    queue:
      name: logs_queue
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

jwt:
  private:
    key: ${RSA_PRIVATE_KEY}
  public:
    key: ${RSA_PUBLIC_KEY}
  exp-business-admin: 604800 #3600
  exp-property-owner: 604800 #86400
  exp-customer: 604800

stripe:
  apiKey: ${STRIPE_API_KEY}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}

logs:
  private-key: ${RSA_LOGS_PRIVATE_KEY}
  public-key: ${RSA_LOGS_PUBLIC_KEY}

management:
  endpoint:
    shutdown:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG