on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - dev
      - master
    paths:
      - 'backend/**'

  workflow_dispatch:

name: Backend Workflow
jobs:
  Checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

  InstallDependenciesAndBuild:
    runs-on: self-hosted
    needs: [Checkout]
    steps:
      - working-directory: backend
        run: mvn install -DskipTests
      - working-directory: backend
        run: mvn compile

  UnitTesting:
    runs-on: self-hosted
    needs: [InstallDependenciesAndBuild]
    steps:
      - working-directory: backend
        run: mvn verify   
      - uses: actions/upload-artifact@v4
        with:
          name: jacoco-code-coverage-results
          path: "${{ github.workspace }}/backend/target/site/jacoco"     

  SonarQubeScan:
    runs-on: self-hosted
    needs: [UnitTesting]
    steps:
      - run: touch sonar-project.properties
      - uses: DamianReeves/write-file-action@master
        with:
          path: sonar-project.properties
          write-mode: overwrite
          contents: |
            sonar.projectKey=desofs-backend
            sonar.sources=backend/src/
            sonar.java.binaries=backend/target/
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}    

  DependencyAnalysis:
    runs-on: self-hosted
    needs: [SonarQubeScan]
    steps:
      - working-directory: backend
        run: dependency-check.sh --out ../ --scan .
      - uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-checker-results
          path: "${{ github.workspace }}/dependency-check-report.html"
