name: Tripnau FE Workflow

on:
  push:
    branches:
      - development
    paths:
      - '**/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: '18.19.0'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
    
    - name: Test
      run: npm run test