on:
  push:
    branches:
      - dev
    paths:
      - 'frontend/**'
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - dev
      - master
    paths:
      - 'frontend/**'

  workflow_dispatch:

name: Frontend Workflow
jobs:
  Checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

  SecretScanner:
    runs-on: self-hosted
    needs: [Checkout]
    steps:
      - run: |
          NOW=$(date +'%Y-%m-%d_%Hh%Mm%Ss')
          SHA_SHORT=$(git rev-parse --short HEAD)
          echo "NOW=$NOW" >> $GITHUB_ENV
          echo "SHA_SHORT=$SHA_SHORT" >> $GITHUB_ENV
      - run: python detect-new-secrets.py resolve_secrets_${{ env.SHA_SHORT }}_${{ env.NOW }}

  InstallDependenciesAndBuild:
    runs-on: self-hosted
    needs: [SecretScanner]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "18.19.0"
      - working-directory: frontend
        run: npm install && npm run build

  UnitTesting:
    runs-on: self-hosted
    needs: [InstallDependenciesAndBuild]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "18.19.0"
      - working-directory: frontend
        run: npm run ci:test
      - uses: actions/upload-artifact@v4
        with:
          name: karma-code-coverage-results
          path: "${{ github.workspace }}/frontend/coverage"         

  SonarQubeScan:
    runs-on: self-hosted
    needs: [UnitTesting]
    steps:
      - run: touch sonar-project.properties
      - uses: DamianReeves/write-file-action@master
        with:
          path: sonar-project.properties
          write-mode: overwrite
          contents: |
            sonar.projectKey=desofs-frontend
            sonar.sources=frontend/src/
            sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}    

  DependencyAnalysis:
    runs-on: self-hosted
    needs: [SonarQubeScan]
    steps:
      - working-directory: frontend
        run: dependency-check.sh --disableYarnAudit --out ../ --scan .
      - uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-checker-results
          path: "${{ github.workspace }}/dependency-check-report.html"  


